export const CommonSelectors = {
  treeTooltip: '[role="tooltip"]',
  checkbox: '[type="checkbox"]',
  tableRow: '[role="row"]',
  columnHeader: '[role=columnheader]',
  columnSwitch: '.react-switch-bg',
  fillSpace: 'textarea[placeholder="Enter text"]',
  tagInput: '[type="text"]',
  selectAll: '.text-blue-bright',
  preset: '.Dropdown-option',
  checkBoxList: 'div.mt-5.h-60.overflow-y-scroll',
  checkBoxListInDrawer: 'div.mt-4.h-auto.overflow-auto',
  tagNameInDrawer: 'span.text-12.ml-1',
  tableCell: '[role="cell"]',
  checkboxWithTag: 'div.flex.items-center.mb-4',
}
