export const DecisionTreeModal = {
  selectAllFromAttribute: 'select-all',
  clearAllFromAttribute: 'clear-all',
  addSelectedAttributes: 'add-selected',
  addByJoin: 'add-by-joining',
  joinByAnd: 'join-by-and',
  joinByOr: 'join-by-or',
  joinByLabel: 'join-by',
  leftInput: 'left-input',
  rightInput: 'right-input',
  replaceButton: 'replace-button',
  selectReset: 'select-reset',
  addButton: 'add-button',
  removeButton: 'remove-button',
  cancelButton: 'cancel-button',
  modalHeader: 'modal-header',
}
