export const FilterRefinerDataCy = {
  selectPreset: 'select-preset',
  saveDataset: 'save-dataset',
  searchField: 'search-input',
  listElements: 'list-element',
  filterHeader: 'filter-header',
  filterElements: '.text-black',
  addButton: 'add-button',
  clearButton: 'clear-button',
  applyButton: 'apply-button',
  resultsListElement: 'results-list-element',
  variantsNumber: 'variants-number',
  noProblemGroupSelected: 'no-problem-group-selected',
  problemGroup: 'problem-group',
  geneName: 'gene-name',
  selectReset: 'select-reset',
  removeButton: 'remove-button',
  undoButton: 'undo-button',
  redoButton: 'redo-button',
  approxDropdown: 'approx-dropdown',
}
